// Curated seed: period names, date ranges, display colors, and artist names only.
// Every fact, date, bio, image and story is fetched from Wikipedia / Wikidata /
// Wikimedia Commons by etl/fetch.mjs — nothing here is generated content.
//
// DO NOT RE-SEED (tried, ended below the 8-painting minimum and were pruned;
// mostly in-copyright artists whose works Commons cannot host):
// Andrei Rublev(4), Victor Vasarely(1), Emil Nolde(3), Oskar Kokoschka(2),
// Leonora Carrington(4), Helen Frankenthaler(1), Lee Krasner(0), Franz Kline(0),
// Richard Hamilton(1), Jasper Johns(3), Robert Rauschenberg(2), Tom Wesselmann(0),
// James Rosenquist(0), Yayoi Kusama(0), Damien Hirst(2), Lucian Freud(5).

export const PERIODS = [
  {
    slug: 'medieval',
    name: 'Medieval',
    wiki: 'Medieval_art',
    start: 500, end: 1400,
    color: '#8a6f4d',
    artists: ['Cimabue', 'Duccio', 'Giotto'],
  },
  {
    slug: 'gothic',
    name: 'Gothic',
    wiki: 'Gothic_art',
    start: 1140, end: 1450,
    color: '#5d6b8a',
    artists: ['Simone Martini', 'Gentile da Fabriano', 'Ambrogio Lorenzetti', 'Pietro Lorenzetti', 'Fra Angelico', 'Sassetta', 'Giovanni di Paolo', 'Lorenzo Monaco', 'Bernardo Daddi'],
  },
  {
    slug: 'renaissance',
    name: 'Renaissance',
    wiki: 'Renaissance_art',
    start: 1400, end: 1600,
    color: '#a3423c',
    artists: ['Jan van Eyck', 'Sandro Botticelli', 'Leonardo da Vinci', 'Albrecht Dürer', 'Michelangelo', 'Raphael', 'Titian', 'Pieter Bruegel the Elder', 'Giovanni Bellini', 'Hieronymus Bosch', 'El Greco', 'Piero della Francesca', 'Andrea Mantegna', 'Hans Holbein the Younger', 'Tintoretto', 'Paolo Veronese', 'Masaccio', 'Filippo Lippi', 'Domenico Ghirlandaio', 'Pietro Perugino', 'Giorgione', 'Antonio da Correggio', 'Lucas Cranach the Elder', 'Rogier van der Weyden', 'Hans Memling', 'Paolo Uccello', 'Giuseppe Arcimboldo', 'Antonello da Messina', 'Vittore Carpaccio', 'Lorenzo Lotto', 'Parmigianino', 'Bronzino', 'Sofonisba Anguissola'],
  },
  {
    slug: 'baroque',
    name: 'Baroque',
    wiki: 'Baroque_painting',
    start: 1590, end: 1750,
    color: '#6d3b1f',
    artists: ['Caravaggio', 'Peter Paul Rubens', 'Artemisia Gentileschi', 'Diego Velázquez', 'Rembrandt', 'Johannes Vermeer', 'Frans Hals', 'Anthony van Dyck', 'Nicolas Poussin', 'Georges de La Tour', 'Bartolomé Esteban Murillo', 'Jacob van Ruisdael', 'Guido Reni', 'Annibale Carracci', 'Jusepe de Ribera', 'Francisco de Zurbarán', 'Pieter de Hooch', 'Jan Steen', 'Claude Lorrain', 'Judith Leyster', 'Aelbert Cuyp', 'Rachel Ruysch', 'Gerrit Dou', 'Gabriël Metsu', 'Gerard ter Borch', 'Jacob Jordaens', 'David Teniers the Younger', 'Jan Brueghel the Elder'],
  },
  {
    slug: 'rococo',
    name: 'Rococo',
    wiki: 'Rococo',
    start: 1700, end: 1780,
    color: '#c98da4',
    artists: ['Antoine Watteau', 'Giovanni Battista Tiepolo', 'François Boucher', 'Jean-Honoré Fragonard', 'Canaletto', 'Thomas Gainsborough', 'Jean Siméon Chardin', 'William Hogarth', 'Joshua Reynolds', 'Francesco Guardi', 'Jean-Baptiste Greuze', 'George Stubbs', 'Bernardo Bellotto', 'Pietro Longhi', 'Jean-Étienne Liotard'],
  },
  {
    slug: 'neoclassicism',
    name: 'Neoclassicism',
    wiki: 'Neoclassicism',
    start: 1760, end: 1830,
    color: '#7d8471',
    artists: ['Jacques-Louis David', 'Angelica Kauffman', 'Jean-Auguste-Dominique Ingres', 'Benjamin West', 'Élisabeth Vigée Le Brun', 'Anton Raphael Mengs', 'John Singleton Copley', 'François Gérard', 'Joseph Wright of Derby', 'Gilbert Stuart', 'Pompeo Batoni'],
  },
  {
    slug: 'romanticism',
    name: 'Romanticism',
    wiki: 'Romanticism',
    start: 1780, end: 1850,
    color: '#4f6152',
    artists: ['Francisco Goya', 'J. M. W. Turner', 'Caspar David Friedrich', 'Théodore Géricault', 'Eugène Delacroix', 'William Blake', 'John Constable', 'Ivan Aivazovsky', 'Karl Bryullov', 'Thomas Cole', 'Frederic Edwin Church', 'Albert Bierstadt', 'Francesco Hayez', 'Johan Christian Dahl', 'Paul Delaroche', 'Théodore Chassériau', 'Edwin Landseer', 'Orest Kiprensky', 'Richard Parkes Bonington'],
  },
  {
    slug: 'realism',
    name: 'Realism',
    wiki: 'Realism_(art_movement)',
    start: 1840, end: 1885,
    color: '#5b524a',
    artists: ['Jean-François Millet', 'Gustave Courbet', 'Winslow Homer', 'Ilya Repin', 'Honoré Daumier', 'Rosa Bonheur', 'Thomas Eakins', 'Mihály Munkácsy', 'James McNeill Whistler', 'Jean-Baptiste-Camille Corot', 'Adolph Menzel', 'Ivan Shishkin', 'Vasily Perov', 'Jules Bastien-Lepage', 'Jules Breton', 'Jean-Léon Gérôme', 'William-Adolphe Bouguereau', 'Lawrence Alma-Tadema', 'Ivan Kramskoi', 'Isaac Levitan', 'John Everett Millais'],
  },
  {
    slug: 'impressionism',
    name: 'Impressionism',
    wiki: 'Impressionism',
    start: 1860, end: 1895,
    color: '#7fa8c9',
    artists: ['Édouard Manet', 'Camille Pissarro', 'Edgar Degas', 'Claude Monet', 'Pierre-Auguste Renoir', 'Berthe Morisot', 'Mary Cassatt', 'Alfred Sisley', 'Gustave Caillebotte', 'Pál Szinyei Merse', 'Frédéric Bazille', 'John Singer Sargent', 'Joaquín Sorolla', 'Anders Zorn', 'Max Liebermann', 'Peder Severin Krøyer', 'Childe Hassam', 'William Merritt Chase', 'Valentin Serov', 'Eugène Boudin', 'Anna Ancher'],
  },
  {
    slug: 'post-impressionism',
    name: 'Post-Impressionism',
    wiki: 'Post-Impressionism',
    start: 1885, end: 1910,
    color: '#d9a441',
    artists: ['Paul Cézanne', 'Paul Gauguin', 'Vincent van Gogh', 'Georges Seurat', 'Henri de Toulouse-Lautrec', 'Henri Rousseau', 'Paul Signac', 'Gustav Klimt', 'Odilon Redon', 'Tivadar Csontváry Kosztka', 'Pierre Bonnard', 'Édouard Vuillard', 'Félix Vallotton', 'Ferdinand Hodler', 'Mikhail Vrubel', 'James Ensor', 'Théo van Rysselberghe', 'Giovanni Segantini', 'Akseli Gallen-Kallela', 'József Rippl-Rónai', 'Arnold Böcklin', 'Vilhelm Hammershøi', 'Ramon Casas'],
  },
  {
    slug: 'expressionism',
    name: 'Expressionism',
    wiki: 'Expressionism',
    start: 1905, end: 1935,
    color: '#b0563b',
    artists: ['Edvard Munch', 'Ernst Ludwig Kirchner', 'Franz Marc', 'Egon Schiele', 'Amedeo Modigliani', 'Wassily Kandinsky', 'Paula Modersohn-Becker', 'August Macke', 'Alexej von Jawlensky', 'Marianne von Werefkin', 'Chaïm Soutine', 'Paul Klee', 'Richard Gerstl', 'Amrita Sher-Gil'],
  },
  {
    slug: 'cubism',
    name: 'Cubism',
    wiki: 'Cubism',
    start: 1907, end: 1930,
    color: '#8c7f6d',
    artists: ['Pablo Picasso', 'Jean Metzinger', 'Albert Gleizes', 'Juan Gris', 'Robert Delaunay', 'Georges Braque', 'Fernand Léger', 'María Blanchard', 'Roger de La Fresnaye', 'Piet Mondrian', 'Kazimir Malevich'],
  },
  {
    slug: 'surrealism',
    name: 'Surrealism',
    wiki: 'Surrealism',
    start: 1920, end: 1955,
    color: '#4a5d8f',
    artists: ['Giorgio de Chirico', 'Max Ernst', 'René Magritte', 'Salvador Dalí', 'Frida Kahlo', 'Joan Miró', 'Yves Tanguy', 'Marc Chagall', 'Paul Delvaux'],
  },
  {
    slug: 'abstract-expressionism',
    name: 'Abstract Expressionism',
    wiki: 'Abstract_expressionism',
    start: 1943, end: 1965,
    color: '#3f3f46',
    artists: ['Arshile Gorky', 'Jackson Pollock', 'Willem de Kooning', 'Mark Rothko', 'Barnett Newman'],
  },
  {
    slug: 'pop-art',
    name: 'Pop Art',
    wiki: 'Pop_art',
    start: 1955, end: 1975,
    color: '#d94f70',
    artists: ['Andy Warhol', 'Roy Lichtenstein', 'David Hockney'],
  },
  {
    slug: 'contemporary',
    name: 'Contemporary',
    wiki: 'Contemporary_art',
    start: 1970, end: 2026,
    color: '#3d8f83',
    artists: ['Jean-Michel Basquiat', 'Keith Haring', 'Gerhard Richter', 'Banksy', 'Anselm Kiefer', 'Francis Bacon (artist)'],
  },
];
